import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { generateGamutBoundaryTable } from "@gamut-plane/core";

const options = { hueSteps: 120, lightnessSteps: 65, searchIterations: 14 };
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(scriptDirectory, "../src/generated/gamutTables.ts");

interface GeneratedBoundaryTable {
  chromaMax: Float32Array;
}

function encode(table: GeneratedBoundaryTable): string {
  const bytes = Buffer.allocUnsafe(table.chromaMax.length * Float32Array.BYTES_PER_ELEMENT);
  for (let index = 0; index < table.chromaMax.length; index += 1) {
    bytes.writeFloatLE(table.chromaMax[index]!, index * Float32Array.BYTES_PER_ELEMENT);
  }
  return bytes.toString("base64");
}

function chunks(value: string): string[] {
  return value.match(/.{1,120}/g) ?? [];
}

async function generateSource(): Promise<string> {
  const srgb = encode(generateGamutBoundaryTable("srgb", options));
  const displayP3 = encode(generateGamutBoundaryTable("display-p3", options));
  const digest = createHash("sha256").update(srgb).update(displayP3).digest("hex");

  return `// Generated by pnpm --filter @gamut-plane/vue generate:gamut-tables.
// Source facts: @gamut-plane/core generateGamutBoundaryTable at ${JSON.stringify(options)}.
import type { GamutBoundaryTable, PickerGamutBoundaryTables } from "@gamut-plane/core";

export const PICKER_GAMUT_TABLE_DIGEST =
  "sha256:${digest}";
const HUE_STEPS = ${options.hueSteps};
const LIGHTNESS_STEPS = ${options.lightnessSteps};

const SRGB_BASE64 = [
${chunks(srgb)
  .map((chunk) => `  "${chunk}",`)
  .join("\n")}
].join("");

const DISPLAY_P3_BASE64 = [
${chunks(displayP3)
  .map((chunk) => `  "${chunk}",`)
  .join("\n")}
].join("");

function decodeTable(gamut: GamutBoundaryTable["gamut"], encoded: string): GamutBoundaryTable {
  const binary = atob(encoded);
  const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0));
  const data = new DataView(bytes.buffer);
  const chromaMax = new Float32Array(bytes.byteLength / Float32Array.BYTES_PER_ELEMENT);
  for (let index = 0; index < chromaMax.length; index += 1) {
    chromaMax[index] = data.getFloat32(index * Float32Array.BYTES_PER_ELEMENT, true);
  }
  return { gamut, hueSteps: HUE_STEPS, lightnessSteps: LIGHTNESS_STEPS, chromaMax };
}

export const PICKER_GAMUT_TABLES: PickerGamutBoundaryTables = {
  srgb: decodeTable("srgb", SRGB_BASE64),
  displayP3: decodeTable("display-p3", DISPLAY_P3_BASE64),
};
`;
}

const source = await generateSource();

if (process.argv.includes("--check")) {
  let checkedIn;
  try {
    checkedIn = await readFile(outputPath, "utf8");
  } catch {
    throw new Error(
      `Gamut tables are missing at ${outputPath}. Run pnpm --filter @gamut-plane/vue generate:gamut-tables.`,
    );
  }
  if (checkedIn !== source) {
    throw new Error(
      "Gamut tables are stale. Run pnpm --filter @gamut-plane/vue generate:gamut-tables and commit the generated file.",
    );
  }
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, source, "utf8");
}
