/** Shared generalized anatomy; adapters render their own native markup and lifecycle. */
export const gpPart = {
  workspace: "workspace",
  field: "field",
  controls: "controls",
  plane: "plane",
  surface: "surface",
  canvas: "canvas",
  domainBoundary: "domain-boundary",
  gamutGuides: "gamut-guides",
  gamutBoundary: "gamut-boundary",
  boundaryHit: "boundary-hit",
  marker: "marker",
  referenceConnector: "reference-connector",
  referenceWarning: "reference-warning",
  axis: "axis",
  axisEnd: "axis-end",
  renderStatus: "render-status",
  viewportControls: "viewport-controls",
  viewportButton: "viewport-button",
  viewportZoom: "viewport-zoom",
  viewportInstructions: "viewport-instructions",
  viewportStatus: "viewport-status",
  channel: "channel",
  channelSymbol: "channel-symbol",
  channelHeader: "channel-header",
  numericInput: "numeric-input",
  channelTrack: "channel-track",
  channelField: "channel-field",
  nativeRange: "native-range",
  gamutInterval: "gamut-interval",
  representationControl: "representation-control",
  authorshipContext: "authorship-context",
  inspectionReadout: "inspection-readout",
  gamuts: "gamuts",
  gamutTrigger: "gamut-trigger",
  gamutSummary: "gamut-summary",
  gamutPopup: "gamut-popup",
  gamutContextMenu: "gamut-context-menu",
  gamutRow: "gamut-row",
  exactResult: "exact-result",
  guidePreference: "guide-preference",
  referenceChoice: "reference-choice",
  availabilityMessage: "availability-message",
} as const;

export type GpPart = (typeof gpPart)[keyof typeof gpPart];

/** Attributes shared by both adapters. */
export const gpAttribute = {
  root: "data-gp-root",
  part: "data-gp-part",
  view: "data-gp-view",
  gamut: "data-gp-gamut",
  marker: "data-gp-marker",
  axis: "data-gp-axis",
  channel: "data-gp-channel",
  status: "data-gp-status",
  overflow: "data-gp-overflow",
  pointerFocus: "data-gp-pointer-focus",
  viewport: "data-gp-viewport",
  viewportZoom: "data-gp-viewport-zoom",
  viewportArmed: "data-gp-viewport-armed",
  viewportPanning: "data-gp-viewport-panning",
  close: "data-gp-close",
  visuallyHidden: "data-gp-visually-hidden",
} as const;

export const gpMarker = { active: "active", reference: "reference" } as const;
export const gpAxis = { x: "x", y: "y" } as const;
export const gpGamut = { srgb: "srgb", displayP3: "display-p3" } as const;
