import { afterEach, describe, expect, it, vi } from "vitest";
import {
  authorEditorPoint,
  editOperationDefinitions,
} from "../../src/capabilities/editOperationDefinitions.js";
import { editorDefinitions } from "../../src/capabilities/editorDefinitions.js";
import {
  geometryDefinitions,
  keyboardGeometryPoint,
} from "../../src/capabilities/geometryDefinitions.js";
import type { BuiltinGeometryProjection } from "../../src/capabilities/types/editingDefinitions.js";
import type {
  RgbChannelEdit,
  RgbRepresentationId,
} from "../../src/capabilities/types/rgbEditing.js";
import { represent } from "../../src/color/represent.js";
import { createColorValue, definitionOf, definingEquals } from "../../src/color/value.js";
import type { ColorRepresentation } from "../../src/color/representation.js";
import type { ColorResult } from "../../src/result.js";

vi.mock("../../src/color/represent.js", async (original) => {
  const actual = await original<typeof import("../../src/color/represent.js")>();
  return { ...actual, represent: vi.fn(actual.represent) };
});
afterEach(() => vi.clearAllMocks());

function value<T>(result: ColorResult<T, unknown>): T {
  if (!result.ok) throw new Error("Fixture operation failed");
  return result.value;
}

// Expected tuples, axes and points are independent fixtures, never generated by the binding math.
const bindings = [
  {
    editorId: "srgb-rg",
    representationId: "srgb",
    geometryId: "srgb-rg-rectangle",
    operationId: "srgb-rg-point",
    axes: ["srgb.r", "srgb.g", "srgb.b"],
    raw: { x: 1.2, y: 0.6 },
    coordinates: { x: 1.2, y: 0.4, fixed: -0.1 },
    edited: [0.6, 0.7, -0.1],
    constrained: [1, 1, -0.1],
    keyboardSource: [0.25, 0.5, -0.1],
  },
  {
    editorId: "srgb-rb",
    representationId: "srgb",
    geometryId: "srgb-rb-rectangle",
    operationId: "srgb-rb-point",
    axes: ["srgb.r", "srgb.b", "srgb.g"],
    raw: { x: 1.2, y: 1.1 },
    coordinates: { x: 1.2, y: -0.1, fixed: 0.4 },
    edited: [0.6, 0.4, 0.7],
    constrained: [1, 0.4, 1],
    keyboardSource: [0.25, 1.2, 0.5],
  },
  {
    editorId: "srgb-gb",
    representationId: "srgb",
    geometryId: "srgb-gb-rectangle",
    operationId: "srgb-gb-point",
    axes: ["srgb.g", "srgb.b", "srgb.r"],
    raw: { x: 0.4, y: 1.1 },
    coordinates: { x: 0.4, y: -0.1, fixed: 1.2 },
    edited: [1.2, 0.6, 0.7],
    constrained: [1.2, 1, 1],
    keyboardSource: [-0.1, 0.25, 0.5],
  },
  {
    editorId: "display-p3-rg",
    representationId: "display-p3",
    geometryId: "display-p3-rg-rectangle",
    operationId: "display-p3-rg-point",
    axes: ["display-p3.r", "display-p3.g", "display-p3.b"],
    raw: { x: 1.2, y: 0.6 },
    coordinates: { x: 1.2, y: 0.4, fixed: -0.1 },
    edited: [0.6, 0.7, -0.1],
    constrained: [1, 1, -0.1],
    keyboardSource: [0.25, 0.5, -0.1],
  },
  {
    editorId: "display-p3-rb",
    representationId: "display-p3",
    geometryId: "display-p3-rb-rectangle",
    operationId: "display-p3-rb-point",
    axes: ["display-p3.r", "display-p3.b", "display-p3.g"],
    raw: { x: 1.2, y: 1.1 },
    coordinates: { x: 1.2, y: -0.1, fixed: 0.4 },
    edited: [0.6, 0.4, 0.7],
    constrained: [1, 0.4, 1],
    keyboardSource: [0.25, 1.2, 0.5],
  },
  {
    editorId: "display-p3-gb",
    representationId: "display-p3",
    geometryId: "display-p3-gb-rectangle",
    operationId: "display-p3-gb-point",
    axes: ["display-p3.g", "display-p3.b", "display-p3.r"],
    raw: { x: 0.4, y: 1.1 },
    coordinates: { x: 0.4, y: -0.1, fixed: 1.2 },
    edited: [1.2, 0.6, 0.7],
    constrained: [1.2, 1, 1],
    keyboardSource: [-0.1, 0.25, 0.5],
  },
] as const;

describe.each(bindings)("native $editorId contracts", (binding) => {
  const editor = editorDefinitions[binding.editorId];
  const geometry = geometryDefinitions[binding.geometryId];
  const operation = editOperationDefinitions[binding.operationId];
  function source(channels: ColorRepresentation<"srgb">["channels"] = [1.2, 0.4, -0.1]) {
    return value(createColorValue({ space: binding.representationId, channels, alpha: -0 }));
  }

  it("correlates encoded axes, geometry and selected-editor point operation", () => {
    expect(editor).toEqual({
      id: binding.editorId,
      representationId: binding.representationId,
      geometryId: binding.geometryId,
      pointOperationId: binding.operationId,
    });
    expect([geometry.x, geometry.y, geometry.fixed]).toEqual(binding.axes);
    expect(operation.request).toEqual({
      representationId: binding.representationId,
      geometryId: binding.geometryId,
      kind: "point",
    });
    expect(operation.geometryId).toBe(binding.geometryId);
    expect(geometry.domain).toEqual({ kind: "rectangle", x: [0, 1], y: [0, 1] });
    expect([geometry.xDirection, geometry.yDirection]).toEqual(["increasing", "decreasing"]);
    expect(Object.isFrozen(geometry.domain.x)).toBe(true);
    expect(Object.isFrozen(geometry.domain.y)).toBe(true);
    expect(Object.isFrozen(operation)).toBe(true);
    expect(Object.isFrozen(operation.request)).toBe(true);
    expect(geometry).not.toHaveProperty("sampleField");
  });

  it("successfully projects raw overflow with its actual fixed channel and alpha", () => {
    const input = source();
    const before = definitionOf(input);
    const projection = value<BuiltinGeometryProjection>(geometry.project(input));
    expect(projection).toEqual({
      representationId: binding.representationId,
      geometryId: binding.geometryId,
      representation: before,
      point: binding.raw,
      coordinates: binding.coordinates,
      channels: { x: binding.axes[0], y: binding.axes[1], fixed: binding.axes[2] },
    });
    expect(geometry.contains(projection.point)).toBe(false);
    expect(definitionOf(input)).toBe(before);
    expect(vi.mocked(represent).mock.calls.map((call) => call[1])).toEqual([
      binding.representationId,
    ]);
  });

  it("keeps coordinate conversion raw and orients positive Y upward", () => {
    expect(geometry.toPoint(-0.25, 1.5)).toEqual({ x: -0.25, y: -0.5 });
    expect(geometry.fromPoint({ x: -0.25, y: -0.5 })).toEqual({ x: -0.25, y: 1.5 });
    for (const [x, y, point] of [
      [0, 0, { x: 0, y: 1 }],
      [1, 1, { x: 1, y: 0 }],
      [0.25, 0.75, { x: 0.25, y: 0.25 }],
    ] as const) {
      expect(geometry.toPoint(x, y)).toEqual(point);
      expect(geometry.fromPoint(point)).toEqual({ x, y });
    }
    const rawCoordinates = geometry.fromPoint(binding.raw);
    expect(rawCoordinates.x).toBe(binding.coordinates.x);
    expect(rawCoordinates.y).toBeCloseTo(binding.coordinates.y, 14);
  });

  it("separates nominal square membership from any finite fixed slice", () => {
    for (const point of [
      { x: 0, y: 0 },
      { x: 1, y: 1 },
      { x: 0.25, y: 0.75 },
    ])
      expect(geometry.contains(point)).toBe(true);
    for (const point of [
      { x: -Number.EPSILON, y: 0.5 },
      { x: 1 + Number.EPSILON, y: 0.5 },
      { x: 0.5, y: -0.1 },
      { x: 0.5, y: 1.1 },
    ])
      expect(geometry.contains(point)).toBe(false);
    for (const fixed of [-0.1, -0, 0, 1, 1.2, 1e308])
      expect(geometry.samplingFixed(fixed)).toBe(fixed);
    for (const fixed of [null, NaN, Infinity, -Infinity])
      expect(geometry.samplingFixed(fixed)).toBeNull();
  });

  it("authors exactly its two channels, retaining the extended fixed value and alpha", () => {
    const input = source();
    const before = definitionOf(input);
    const point = Object.freeze({ x: 0.6, y: 0.3 });
    const edited = value(authorEditorPoint(input, editor, point));
    expect(definitionOf(edited)).toEqual({
      space: binding.representationId,
      channels: binding.edited,
      alpha: -0,
    });
    expect(definitionOf(input)).toBe(before);
    expect(point).toEqual({ x: 0.6, y: 0.3 });
    expect(vi.mocked(represent).mock.calls.map((call) => call[1])).toEqual([
      binding.representationId,
    ]);
  });

  it("authors a converted fixed channel in the selected RGB encoding", () => {
    const input = value(
      createColorValue({ space: "oklab", channels: [0.6, 0.12, -0.08], alpha: 0.372913 }),
    );
    const before = definitionOf(input);
    const observed = value(represent(input, binding.representationId));
    const expected =
      binding.editorId === "srgb-rg" || binding.editorId === "display-p3-rg"
        ? [0.6, 0.7, observed.channels[2]]
        : binding.editorId === "srgb-rb" || binding.editorId === "display-p3-rb"
          ? [0.6, observed.channels[1], 0.7]
          : [observed.channels[0], 0.6, 0.7];
    vi.clearAllMocks();
    const edited = value(authorEditorPoint(input, editor, { x: 0.6, y: 0.3 }));
    expect(definitionOf(edited)).toEqual({
      space: binding.representationId,
      channels: expected,
      alpha: 0.372913,
    });
    expect(vi.mocked(represent)).toHaveBeenCalledExactlyOnceWith(input, binding.representationId);
    expect(definitionOf(input)).toBe(before);
  });

  it("authors natively when the extended fixed channel prevents OKLCH observation", () => {
    const channels =
      binding.editorId === "srgb-rg" || binding.editorId === "display-p3-rg"
        ? ([0.25, 0.5, 1e308] as const)
        : binding.editorId === "srgb-rb" || binding.editorId === "display-p3-rb"
          ? ([0.25, 1e308, 0.5] as const)
          : ([1e308, 0.25, 0.5] as const);
    const expected =
      binding.editorId === "srgb-rg" || binding.editorId === "display-p3-rg"
        ? [0.6, 0.7, 1e308]
        : binding.editorId === "srgb-rb" || binding.editorId === "display-p3-rb"
          ? [0.6, 1e308, 0.7]
          : [1e308, 0.6, 0.7];
    const input = source(channels);
    expect(represent(input, "oklch").ok).toBe(false);
    vi.clearAllMocks();
    const edited = value(authorEditorPoint(input, editor, { x: 0.6, y: 0.3 }));
    expect(definitionOf(edited)).toEqual({
      space: binding.representationId,
      channels: expected,
      alpha: -0,
    });
    expect(vi.mocked(represent)).toHaveBeenCalledExactlyOnceWith(input, binding.representationId);
    expect(definitionOf(input).channels).toEqual(channels);
  });

  it("constrains explicit interaction inputs without constraining raw conversion", () => {
    const point = { x: 2, y: -1 };
    expect(geometry.fromPoint(point)).toEqual({ x: 2, y: 2 });
    expect(geometry.constrain(point)).toEqual({ x: 1, y: 0 });
    const edited = value(authorEditorPoint(source(), editor, point));
    expect(definitionOf(edited).channels).toEqual(binding.constrained);
    expect(
      geometry.contains(value<BuiltinGeometryProjection>(geometry.project(edited)).point),
    ).toBe(true);
    expect(point).toEqual({ x: 2, y: -1 });
  });

  it("preserves signed-zero fixed coordinates and unrounded alpha", () => {
    const input = value(
      createColorValue({
        space: binding.representationId,
        channels: [-0, -0, -0],
        alpha: 0.372913123456789,
      }),
    );
    const edited = value(authorEditorPoint(input, editor, { x: 0.123456789012345, y: 0.3 }));
    const projected = value<BuiltinGeometryProjection>(geometry.project(edited));
    expect(Object.is(projected.coordinates.fixed, -0)).toBe(true);
    expect(projected.coordinates.x).toBe(0.123456789012345);
    expect(projected.representation.alpha).toBe(0.372913123456789);
  });

  it("applies normalized fine/coarse keyboard steps and Home/End", () => {
    const input = source(binding.keyboardSource);
    const projection = value<BuiltinGeometryProjection>(geometry.project(input));
    expect(projection.point).toEqual({ x: 0.25, y: 0.5 });
    for (const [action, coarse, expected] of [
      ["increase-x", false, { x: 0.255, y: 0.5 }],
      ["decrease-x", true, { x: 0.23, y: 0.5 }],
      ["increase-y", false, { x: 0.25, y: 0.495 }],
      ["decrease-y", true, { x: 0.25, y: 0.52 }],
      ["minimum-x", false, { x: 0, y: 0.5 }],
      ["maximum-x", true, { x: 1, y: 0.5 }],
    ] as const) {
      expect(keyboardGeometryPoint(projection, action, coarse)).toEqual(expected);
      expect(geometry.contains(expected)).toBe(true);
    }
    expect(definitionOf(input).channels).toEqual(binding.keyboardSource);
  });

  it("recovers overflow only through an explicit constrained keyboard edit", () => {
    const input = source();
    const before = definitionOf(input);
    const projection = value<BuiltinGeometryProjection>(geometry.project(input));
    expect(projection.point).toEqual(binding.raw);
    for (const action of [
      "increase-x",
      "decrease-x",
      "increase-y",
      "decrease-y",
      "minimum-x",
      "maximum-x",
    ] as const) {
      const point = keyboardGeometryPoint(projection, action, true);
      expect(geometry.contains(point)).toBe(true);
      expect(definitionOf(input)).toBe(before);
      const edited = value(authorEditorPoint(input, editor, point));
      const nextProjection = value<BuiltinGeometryProjection>(geometry.project(edited));
      expect(geometry.contains(nextProjection.point)).toBe(true);
      expect(nextProjection.coordinates.fixed).toBe(binding.coordinates.fixed);
      expect(nextProjection.representation.alpha).toBe(-0);
    }
    expect(definitionOf(input)).toBe(before);
  });

  it("rejects nonfinite points rather than authoring recovery data", () => {
    for (const point of [
      { x: NaN, y: 0 },
      { x: 0, y: Infinity },
      { x: -Infinity, y: 0 },
    ]) {
      expect(authorEditorPoint(source(), editor, point)).toEqual({
        ok: false,
        error: { code: "invalid-plane-edit" },
      });
      expect(() => geometry.constrain(point)).toThrow(TypeError);
      expect(() => geometry.contains(point)).toThrow(TypeError);
      expect(() => geometry.fromPoint(point)).toThrow(TypeError);
      expect(() => geometry.toPoint(point.x, point.y)).toThrow(TypeError);
    }
    // @ts-expect-error raw conversion must not coerce a numeric string into an RGB coordinate
    expect(() => geometry.toPoint(0.5, "0.5")).toThrow(TypeError);
    // @ts-expect-error missing RGB coordinates are not supported
    expect(() => geometry.toPoint(0.5, null)).toThrow(TypeError);
  });

  it("propagates genuine representation failures instead of reporting overflow", () => {
    const input = value(createColorValue({ space: "oklab", channels: [1e308, 0, 0], alpha: 0.37 }));
    const failure = {
      ok: false,
      error: { code: "numerical-range", from: "oklab", to: binding.representationId },
    };
    expect(geometry.project(input)).toEqual(failure);
    expect(authorEditorPoint(input, editor, { x: 0.6, y: 0.3 })).toEqual(failure);
    expect(definitionOf(input).channels).toEqual([1e308, 0, 0]);
  });
});

function patch(
  input: Parameters<typeof represent>[0],
  representationId: RgbRepresentationId,
  channels: RgbChannelEdit<"srgb">["channels"],
  alpha?: number,
) {
  if (representationId === "srgb") {
    const operation = editOperationDefinitions["srgb-channel-patch"];
    return operation.author(input, {
      ...operation.request,
      channels,
      ...(alpha !== undefined ? { alpha } : {}),
    });
  }
  const operation = editOperationDefinitions["display-p3-channel-patch"];
  return operation.author(input, {
    ...operation.request,
    channels,
    ...(alpha !== undefined ? { alpha } : {}),
  });
}

describe.each(["srgb", "display-p3"] as const)("native %s channel patches", (representationId) => {
  const operation = editOperationDefinitions[`${representationId}-channel-patch`];
  const input = value(
    createColorValue({
      space: representationId,
      channels: [1.2, 0.4, -0.1],
      alpha: 0.372913123456789,
    }),
  );

  it("patches each finite extended channel independently in its selected defining space", () => {
    const before = definitionOf(input);
    for (const [channels, expected] of [
      [{ r: -0.123456789012345 }, [-0.123456789012345, 0.4, -0.1]],
      [{ g: 1.456789012345678 }, [1.2, 1.456789012345678, -0.1]],
      [{ b: -2 }, [1.2, 0.4, -2]],
    ] as const) {
      const next = value(patch(input, representationId, channels));
      expect(definitionOf(next)).toEqual({
        space: representationId,
        channels: expected,
        alpha: before.alpha,
      });
    }
    expect(definitionOf(input)).toBe(before);
    expect(vi.mocked(represent).mock.calls.map((call) => call[1])).toEqual([
      representationId,
      representationId,
      representationId,
    ]);
    expect(operation.geometryId).toBeNull();
    expect(Object.isFrozen(operation)).toBe(true);
    expect(Object.isFrozen(operation.request)).toBe(true);
  });

  it("patches a cross-representation observation rather than relabeling its tuple", () => {
    for (const definition of [
      { space: "oklab", channels: [0.6, 0.12, -0.08], alpha: 0.37 },
      { space: "oklch", channels: [0.6, 0.2, 720], alpha: 0.37 },
      {
        space: representationId === "srgb" ? "display-p3" : "srgb",
        channels: [1.2, 0.4, -0.1],
        alpha: 0.37,
      },
    ] as const) {
      const source = value(createColorValue(definition));
      const before = definitionOf(source);
      const observation = value(represent(source, representationId));
      vi.clearAllMocks();
      const next = value(patch(source, representationId, { g: -0.25 }));
      expect(definitionOf(next)).toEqual({
        space: representationId,
        channels: [observation.channels[0], -0.25, observation.channels[2]],
        alpha: observation.alpha,
      });
      expect(vi.mocked(represent)).toHaveBeenCalledExactlyOnceWith(source, representationId);
      expect(definitionOf(next).channels[0]).not.toBe(definition.channels[0]);
      expect(definitionOf(source)).toBe(before);
    }
  });

  it("retains native numeric values even when an OKLCH observation would fail", () => {
    const source = value(
      createColorValue({ space: representationId, channels: [1e308, 0, 0], alpha: -0 }),
    );
    expect(represent(source, "oklch").ok).toBe(false);
    vi.clearAllMocks();
    const next = value(patch(source, representationId, { g: -0.2 }));
    expect(definitionOf(next)).toEqual({
      space: representationId,
      channels: [1e308, -0.2, 0],
      alpha: -0,
    });
    expect(vi.mocked(represent)).toHaveBeenCalledExactlyOnceWith(source, representationId);
    for (const binding of bindings.filter(
      (candidate) => candidate.representationId === representationId,
    ))
      expect(geometryDefinitions[binding.geometryId].project(source).ok).toBe(true);
  });

  it("preserves signed-zero coordinates and supports deliberate alpha changes", () => {
    const source = value(
      createColorValue({ space: representationId, channels: [-0, -0, -0], alpha: -0 }),
    );
    expect(definingEquals(source, value(patch(source, representationId, { r: -0 })))).toBe(true);
    expect(definitionOf(value(patch(source, representationId, { g: 0.25 })))).toEqual({
      space: representationId,
      channels: [-0, 0.25, -0],
      alpha: -0,
    });
    expect(definitionOf(value(patch(source, representationId, {}, 0.372913)))).toEqual({
      space: representationId,
      channels: [-0, -0, -0],
      alpha: 0.372913,
    });
    const zero = value(patch(source, representationId, { r: 0 }));
    expect(definingEquals(source, zero)).toBe(false);
    expect(
      definingEquals(
        value(patch(source, representationId, { r: 1 })),
        value(patch(source, representationId, { r: 1 + Number.EPSILON })),
      ),
    ).toBe(false);
  });

  it("rejects malformed patches and retains established definition errors for bad coordinates", () => {
    const invalidRequests: readonly unknown[] = [
      null,
      undefined,
      [],
      {},
      operation.request,
      { ...operation.request, channels: {} },
      { ...operation.request, channels: [] },
      { ...operation.request, channels: null },
      { ...operation.request, channels: { h: 20 } },
      { ...operation.request, channels: { r: 0.5 }, geometryId: "srgb-rg-rectangle" },
      { ...operation.request, kind: "point", channels: { r: 0.5 } },
      {
        ...operation.request,
        representationId: representationId === "srgb" ? "display-p3" : "srgb",
        channels: { r: 0.5 },
      },
    ];
    for (const request of invalidRequests) {
      // @ts-expect-error deliberately malformed runtime boundary input
      expect(operation.author(input, request)).toEqual({
        ok: false,
        error: { code: "invalid-plane-edit" },
      });
    }
    for (const coordinate of [NaN, Infinity, -Infinity])
      expect(patch(input, representationId, { r: coordinate })).toEqual({
        ok: false,
        error: { code: "invalid-definition" },
      });
    for (const alpha of [NaN, Infinity, -0.1, 1.1])
      expect(patch(input, representationId, { r: 0.5 }, alpha)).toEqual({
        ok: false,
        error: { code: "invalid-definition" },
      });
    for (const channels of [{ r: undefined }, { r: null }, { r: "0.5" }]) {
      // @ts-expect-error coordinates require actual finite numbers
      expect(patch(input, representationId, channels)).toEqual({
        ok: false,
        error: { code: "invalid-definition" },
      });
    }
    expect(definitionOf(input).channels).toEqual([1.2, 0.4, -0.1]);
  });

  it("propagates genuine conversion failure without replacing the source", () => {
    const source = value(createColorValue({ space: "oklab", channels: [1e308, 0, 0], alpha: 1 }));
    expect(patch(source, representationId, { r: 0.5 })).toEqual({
      ok: false,
      error: { code: "numerical-range", from: "oklab", to: representationId },
    });
    expect(definitionOf(source).space).toBe("oklab");
  });
});

it("rejects mismatched geometry, representation, absent point data and unsupported point fields", () => {
  const operation = editOperationDefinitions["srgb-rg-point"];
  const input = value(createColorValue({ space: "srgb", channels: [1.2, 0.4, -0.1], alpha: 0.37 }));
  for (const edit of [
    null,
    undefined,
    [],
    {},
    operation.request,
    { ...operation.request, point: null },
    { ...operation.request, point: {} },
    { ...operation.request, point: { x: "0.6", y: 0.3 } },
    { ...operation.request, point: { x: 0.6, y: 0.3, fixed: 0 } },
    { ...operation.request, point: { x: 0.6, y: 0.3 }, geometryId: "srgb-rb-rectangle" },
    { ...operation.request, point: { x: 0.6, y: 0.3 }, representationId: "display-p3" },
    { ...operation.request, point: { x: 0.6, y: 0.3 }, channels: { b: 0.2 } },
  ]) {
    // @ts-expect-error deliberately malformed geometry-bound requests
    expect(operation.author(input, edit)).toEqual({
      ok: false,
      error: { code: "invalid-plane-edit" },
    });
  }
  expect(vi.mocked(represent)).not.toHaveBeenCalled();
  expect(
    operation.author(input, { ...operation.request, point: { x: 0.6, y: 0.3 }, alpha: Infinity }),
  ).toEqual({ ok: false, error: { code: "invalid-definition" } });
  expect(
    definitionOf(
      value(
        operation.author(input, { ...operation.request, point: { x: 0.6, y: 0.3 }, alpha: 0.4 }),
      ),
    ),
  ).toEqual({ space: "srgb", channels: [0.6, 0.7, -0.1], alpha: 0.4 });
});
