export const PICKER_ACTIVE_MARKER_RADIUS = 9;

export const PICKER_SLIDER_FIELD_INSET = 5;
export const PICKER_SLIDER_TRACK_HEIGHT = 32;
export const PICKER_SLIDER_THUMB_WIDTH = 10;
export const PICKER_SLIDER_THUMB_TOP = 2;
